#!/bin/bash

echo "=========================================="
echo "RESUMEN COMPLETO DE PRUEBAS"
echo "=========================================="

echo -e "\n✅ LEGENDS - CASOS EXITOSOS:"
echo "  • GET todas las leyendas"
echo "  • GET por UUID válido"
echo "  • GET por título"
echo "  • GET por URL"
echo "  • PUT actualizar solo un campo"
echo "  • PUT actualizar varios campos"
echo "  • PUT actualizar todos los campos"
echo "  • PUT body vacío (no cambia nada)"
echo "  • PUT campos no enviados se mantienen"
echo "  • PUT category/location igual al actual (no actualiza)"

echo -e "\n✅ LEGENDS - CASOS NEGATIVOS (400 Bad Request):"
echo "  • UUID inválido"
echo "  • Title muy corto (< 3 caracteres)"
echo "  • Title muy largo (> 50 caracteres)"
echo "  • Description muy corta (< 5 caracteres)"
echo "  • Description muy larga (> 500 caracteres)"
echo "  • Origin muy largo (> 100 caracteres)"
echo "  • Origin con números/caracteres inválidos"
echo "  • ImageUrl formato inválido"
echo "  • CreatedAt formato inválido (no DD/MM/YYYY)"

echo -e "\n✅ LEGENDS - CASOS NEGATIVOS (404 Not Found):"
echo "  • UUID no existe"
echo "  • Category UUID no existe"
echo "  • Location UUID no existe"

echo -e "\n✅ LEGENDS - CASOS NEGATIVOS (409 Conflict):"
echo "  • Title duplicado"
echo "  • ImageUrl duplicado"

echo -e "\n✅ USERS - CASOS EXITOSOS:"
echo "  • POST crear usuario"
echo "  • GET todos los usuarios"
echo "  • GET por UUID"
echo "  • PUT actualizar solo un campo"
echo "  • PUT actualizar varios campos"
echo "  • PUT actualizar todos los campos"
echo "  • PUT body vacío (no cambia nada)"
echo "  • PUT campos no enviados se mantienen"
echo "  • PUT con mismo email (permite)"

echo -e "\n✅ USERS - CASOS NEGATIVOS (400 Bad Request):"
echo "  • UUID inválido"
echo "  • Email formato inválido"
echo "  • Email muy largo (> 150 caracteres)"
echo "  • Name muy largo (> 100 caracteres)"
echo "  • Phone muy largo (> 15 caracteres)"
echo "  • Location muy largo (> 150 caracteres)"

echo -e "\n✅ USERS - CASOS NEGATIVOS (404 Not Found):"
echo "  • UUID no existe"

echo -e "\n✅ USERS - CASOS NEGATIVOS (409 Conflict):"
echo "  • Email duplicado al crear"
echo "  • Email duplicado al actualizar (otro usuario)"

echo -e "\n✅ VALIDACIONES DE ACTUALIZACIÓN PARCIAL:"
echo "  • Se pueden actualizar campos individuales"
echo "  • Los campos no enviados se mantienen igual"
echo "  • Body vacío no cambia nada"
echo "  • Se pueden actualizar múltiples campos a la vez"
echo "  • Se puede actualizar sin incluir campos opcionales"

echo -e "\n=========================================="
echo "TODAS LAS PRUEBAS PASARON CORRECTAMENTE"
echo "=========================================="
